[package]
name = "rns-tpu"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = { version = "0.9.2", features = ["metal"] }
candle-coreml = "0.3.1"
num-integer = "0.1.46"
num-traits = "0.2.19"
rayon = "1.11.0"
thiserror = "2.0.18"

[dev-dependencies]
criterion = "0.8.1"
rand = "0.8.5"
